tests_func: drop unused S3_PORT EXPOSE from MinIO image
podman complains:

[2/2] STEP 7/8: EXPOSE $S3_PORT
Error: building at STEP "EXPOSE $S3_PORT": EXPOSE requires at least one argument