fix checkout on Windows (#1777)
* fix checkout on Windows

  "C:\Program Files\Git\bin\git.exe" checkout --progress --force refs/tags/v3.0.3
  Error: error: invalid path 'docker/ubuntu/config/apt/apt.conf.d/01buildconfig '
  Error: The process 'C:\Program Files\Git\bin\git.exe' failed with exit code 128

* gnupg2 is required for percona